create table geo_postcode_lookup (
    postcode_7 character varying (7),
    postcode_8 character varying (8),
    postcode character varying (10),
    date_of_introduction character varying (6),
    date_of_termination character varying (6),
    county character varying (9),
    county_electoral_division character varying (9),
    district character varying (9),
    ward character varying (9),
    parish character varying (9),
    user_type integer,
    easting numeric,
    northing numeric,
    positional_quality_indicator integer,
    health_authority character varying (9),
    nhs_region character varying (9),
    country character varying (9),
    region character varying (9),
    standard_statistical_region character varying (1),
    parliamentary_constituency character varying (9),
    european_electoral_region character varying (9),
    local_learning_and_skills_council character varying (9),
    travel_to_work_area character varying (9),
    primary_care_trust character varying (9),
    international_territorial_level character varying (9),
    statistical_ward character varying (6),
    oa_01 character varying (10),
    census_area_statistics_ward character varying (6),
    national_park character varying (9),
    lsoa_01 character varying (9),
    msoa_01 character varying (9),
    urban_rural_indicator_01 character varying (2),
    oa_01_classification character varying (3),
    oa_11 character varying (9),
    lsoa_11 character varying (9),
    msoa_11 character varying (9),
    workplace_zone character varying (9),
    sub_icb_location character varying (9),
    built_up_area character varying (9),
    built_up_area_sub_division character varying (9),
    rural_urban_classification_11 character varying (2),
    oa_classification_11 character varying (9),
    latitude numeric,
    longitude numeric,
    local_enterprise_partnership_1 character varying (9),
    local_enterprise_partnership_2 character varying (9),
    police_force_area character varying (9),
    imd integer,
    cancer_alliance character varying (9),
    integrated_care_board character varying (9),
    oa_21 character varying (9),
    lsoa_21 character varying (9),
    msoa_21 character varying (9)
);

create unique index cuidx_geopostcodelookup_postcode on geo_postcode_lookup (postcode);
cluster geo_postcode_lookup using cuidx_geopostcodelookup_postcode;
create index idx_geopostcodelookup_lsoa on geo_postcode_lookup (lsoa_21);
create index idx_geopostcodelookup_district on geo_postcode_lookup (district);
create index idx_geopostcodelookup_county on geo_postcode_lookup (county);
create index idx_geopostcodelookup_country on geo_postcode_lookup (country);
