create table schemas_staging_libraries (
  local_authority text,
  name text,
  address_1 character varying (250),
  address_2 character varying (250),
  address_3 character varying (250),
  postcode character varying (9),
  unique_property_reference_number text,
  statutory text,
  library_type character varying (50),
  year_opened text,
  year_closed text,
  monday_staffed_hours character varying (100),
  tuesday_staffed_hours character varying (100),
  wednesday_staffed_hours character varying (100),
  thursday_staffed_hours character varying (100),
  friday_staffed_hours character varying (100),
  saturday_staffed_hours character varying (100),
  sunday_staffed_hours character varying (100),
  monday_unstaffed_hours character varying (100),
  tuesday_unstaffed_hours character varying (100),
  wednesday_unstaffed_hours character varying (100),
  thursday_unstaffed_hours character varying (100),
  friday_unstaffed_hours character varying (100),
  saturday_unstaffed_hours character varying (100),
  sunday_unstaffed_hours character varying (100),
  special_hours text,
  colocated text,
  colocated_with character varying (250),
  notes text,
  url text,
  email_address text
);
