create table schemas_services (
  id serial not null,
  local_authority_code character (9),
  local_authority_library_url text,
  service_name text,
  service_url text,
  operator_name text,
  operator_url text,
  catalogue_url text,
  android_app_url text,
  ios_app_url text,
  email text,
  phone text,
  new_member_url text,
  libraries_url text,
  mobile_libraries_url text,
  home_library_service_url text,
  computer_access_url text,
  wifi_access_url text,
  fees_and_charges_url text,
  child_fine text,
  adult_fine numeric,
  fine_interval text,
  fine_notes text,
  fine_free_url text,
  childrens_service_url text,
  instagram_name text,
  facebook_page_name text,
  twitter_handle text,
  youtube_id text,
  flickr_id text,
  events_url text,
  eventbrite_id text,
  google_calendar_id text,
  
  
  Blog URL,Blog RSS feed,News URL,News signup URL,News RSS feed,Podcast name,Podcast URL,Podcast RSS feed,Borrowbox ID,Borrowbox offer,Overdrive name,Overdrive offer,RBDigital name,RBDigital offer,cloudLibrary name,cloudLibrary offer,uLibrary name,uLibrary offer,Ebook info URL,Audiobook info URL,Emagazines info URL,Ebook supplier,Ebook URL,Audiobook supplier,Audiobook URL,Library management system supplier,Library management system,Online catalogue system,Events,Time to read library,Library notification,Services,Green library
  local_authority_code character (9),
  name character varying (250),
  address_1 character varying (250),
  address_2 character varying (250),
  address_3 character varying (250),
  postcode character varying (9),
  statutory boolean not null,
  unique_property_reference_number numeric,
  library_type_id integer,
  year_opened numeric (4),
  year_closed numeric (4),
  monday_staffed_hours character varying (100),
  tuesday_staffed_hours character varying (100),
  wednesday_staffed_hours character varying (100),
  thursday_staffed_hours character varying (100),
  friday_staffed_hours character varying (100),
  saturday_staffed_hours character varying (100),
  sunday_staffed_hours character varying (100),
  monday_unstaffed_hours character varying (100),
  tuesday_unstaffed_hours character varying (100),
  wednesday_unstaffed_hours character varying (100),
  thursday_unstaffed_hours character varying (100),
  friday_unstaffed_hours character varying (100),
  saturday_unstaffed_hours character varying (100),
  sunday_unstaffed_hours character varying (100),
  special_hours text,
  colocated boolean not null,
  colocated_with character varying (250),
  notes text,
  url text,
  email_address text,
  constraint pk_schemaslibraries_id primary key (id),
  constraint fk_schemaslibraries_localauthoritycode foreign key (local_authority_code) references schemas_local_authority (code),
  constraint fk_schemaslibraries_librarytypeid foreign key (library_type_id) references schemas_library_type (id)
);

create index cidx_schemasservices_id on schemas_services (local_authority_code, name);
cluster schemas_services using cidx_schemasservices_id;
