name: Export library data schemas
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Export libraries
          env:
            PGDATABASE: ${{ secrets.PGDATABASE }}
            PGPASSWORD: ${{ secrets.PGPASSWORD }}
            PGPORT: 5432
            PGUSER: ${{ secrets.PGUSER }}
            PGHOST: ${{ secrets.PGHOST }}
        run: psql -f export_libraries.sql
